# Programmazione Euristica: il percorso del Cavallo.

https://it.wikipedia.org/wiki/Percorso_del_cavallo

Il percorso del cavallo è un problema matematico riguardante lo spostarsi di un cavallo su una scacchiera. Il cavallo è posizionato sulla scacchiera vuota e, spostandosi secondo le regole degli scacchi, deve occupare ogni casa esattamente una volta.<br>

https://it.wikipedia.org/wiki/Cavallo_(scacchi)
 Il movimento del cavallo può essere immaginato come la somma di uno spostamento orizzontale di una casa e di uno verticale di due o viceversa, descrivendo una "L". Il cavallo è inoltre l'unico pezzo che, nei suoi movimenti, può attraversare anche caselle già occupate da altri pezzi: si dice che può "saltare". Si noti che a ogni mossa il cavallo cambia il colore della casa in cui si trova.<br>

Dobbiamo scrivere uno script che muova il cavallo sulla scacchiera, rappresentata da un vettore 8x8, inizializzato a 0. Se posizionato al centro, il cavallo potra muoversi in 8 possibili caselle che possiamo numerare da 1 a 8 seguendo il senso orario dal :
![image info](../assets/cavallo.jpg)

Descriviamo le possibili mosse del cavallo su una tupla (h - orizzontale, v - verticale) contente l'incremento lungo gli assi h e v: ad esempio, facendo riferimento alla foto sopra, dalla posizione in cui si trova il cavallo (h=3,v=4), per spostarsi nella posizione 1, in (h=5, v=3), faremo riferimento alla tupla (+2,-1) (due a destra, una in su).


In [2]:
# Rappresentiamo la Scacchiera come un array bidimensionale 8x8 chimato `board`:
# Importiamo le librerie standard di python che ci serviranno in questo progetto:
import random
import collections

# Le librerie dei framework specifici:
import matplotlib.pyplot as plt # Motore grafico di python per realizzare diagrammi e fuznoni
import numpy as np # Libreria che gestisce ad altissima efficienza gli array
import seaborn as sns # Libreria che usa il motore grafico di MatplotLib con funzionalita' grafiche avanzate

Rappresentiamo la scacchiera con un array bidimensionale 8x8 riempito di Zeri. Il cavallo si muove nella scacchiera partendo da una casella che verra' marcata col numero 1. Teniamo traccia degli spostamenti del cavallo incrementando di 1 ogni passaggio, ottenendo dunque un array di questo tipo:
'''
array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  3.,  0.,  0.,  0.,  0.,  0.],
       [ 4.,  0.,  8.,  0.,  2., 17.,  0.,  0.],
       [ 7.,  0.,  5.,  0.,  0.,  0., 13.,  0.],
       [ 0.,  9.,  0.,  1., 18., 11., 16.,  0.],
       [ 0.,  6.,  0., 10.,  0., 14.,  0., 12.],
       [ 0.,  0.,  0.,  0.,  0., 19.,  0., 15.]])
'''
Da questo array si possono vedere tutti i salti che ha fatto il cavallo ha fatto 19 salti (sui 64 possibili) prima di non riuscire piu' a muoversi su caselle mai toccate.


In [8]:
# Scriviamo una funzione che inizializzi il gioco, creando una "board" e posizionando il cavallo nella sua posizione iniziale.
# Consideriamo la possibilita' di far partire il cavallo da una delle sue posizioni "standard"
# o da una posizione casuale nella scacchiera:


def initialize_game(horse_default_position=True):
    
    #Aoi TODO: implementare la possibilità di definire una posizione random
    positions = [(0,1),(0,6),(7,1),(7,6)]
    
    # creo playing chess board 8x8 filled with 0s
    board = np.zeros((8,8))
    
    # scelgo a caso una tra le quattro possibili posizioni di partenza del cavallo
    start_position = random.choice(positions)
    board[start_position] = 1
    
    #do alla cella in posizione [0,1] il valore 1 in modo da segnare la partenza del cavallo in quella cella
    #board[0,1] = 1    
    
    return board


#print(initialize_game())

# Scrviamo una funzione che legge una board e restituisce:
# - il numero di mosse raggunto dal cavallo
# - una tupla con la posizione attuale, orizzontale e verticale
def get_horse_current_position(board):

    #numero di mosse ovvero anche posizione corrente
    current_move_number = board.max()
    
    #current position data il massimo valore della board e srotolando array
    current_h, current_v = np.unravel_index(board.argmax(), (8,8))

    return current_move_number, (current_h, current_v)

#print(get_horse_current_position(board))

# Scriviamo una funzione che legge una board e restituisce una lista delle possibili mosse disponibili
def get_available_moves(board):
    
    possible_movements = [(2,1),(2,-1),(-2,1),(-2,-1),(1,2),(1,-2),(-1,2),(-1,-2)]
    _, current_horse_position = get_horse_current_position(board)
    h_pos, v_pos = current_horse_position

    available_moves = []
    
    for move in possible_movements:
        h_move ,v_move = move
        new_h_pos = h_pos + h_move
        new_v_pos = v_pos + v_move

        if 0 <= new_h_pos <= 7:
            if 0 <= new_v_pos <= 7:
                if board[(new_h_pos,new_v_pos)] == 0:
                    available_moves.append((new_h_pos,new_v_pos))

   
    
    return available_moves


#print(get_available_moves(board))


# Scriviamo una funzione che date le mosse a disposizione, ne sceglie casualmente una e la restituisce
def random_move(available_moves):

    return random.choice(available_moves)

#print(random_move(board))

# Scriviamo una funzione che legge una board e fa fare al cavallo una mossa scegliendo tra le disponibili casualmente

def move_horse(board):
    
    current_move, _ = get_horse_current_position(board)
    next_move_count = current_move + 1

    available_moves = get_available_moves(board)
    if len(available_moves)==0:
        return board,'GAME OVER'
    

    next_move = random_move(available_moves)
    board[next_move]= next_move_count

    available_moves = get_available_moves(board)

    return board, 'Keep Playing'
#print(move_horse(board))


# Scriviamo una funzione che gioca una partita completa sino a che il cavallo non puo' piu' muoversi
# A fine partita, se il parametro "verbose" e' impostato su true, stampa a video la board.
# Restituisce la board
def play_one_game(verbose = False, horse_default_start_position = True):

    board = initialize_game(horse_default_start_position)

    board, status = move_horse(board)
  
    while status != 'GAME OVER':
        board, status = move_horse(board)
    
    if verbose:
        print(board)



    return board

print(play_one_game())

# Scriviamo una funzione che gioca n partite e restituisce un po' di statistiche:
# - Numero partite vinte o miglior partita,
# - Board completate o miglior Board
# - Punteggio raggiunto in media e mediana,
# - Frequenza di occupazione di alcune caselle nella board
# - vvee
def play_multiple_games(n= 100, verbose = False, horse_default_start_position = True, win_game=True):
    
    if win_game:
        pass
    else:
        moves_per_game = {}
        max_n_moves = 0, 0
        for j in range(1, n+1):
            board = play_one_game(verbose,horse_default_start_position)
            n_moves, _ = get_horse_current_position(board)
            
        
        
        



    # return statistics
    pass





[[ 0.  1.  0.  0.  0.  9.  0.  0.]
 [ 0.  0.  0.  2.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  8.  3. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  7.  0.]
 [ 0.  0.  0.  0.  4. 11. 16.  0.]
 [ 0.  0.  0.  0.  0.  6. 13.  0.]
 [ 0.  0.  0.  5. 12. 17.  0. 15.]
 [ 0.  0.  0.  0.  0. 14.  0. 18.]]
